steps:
  env:
  - 'PROJECT_ID=aapaca-backend-api'
  - 'IMAGE_NAME=backend-api'
  - 'SERVICE_NAME=backend-api'
  - 'BUILD_PATH=src/app/'
  - 'REGION=asia-northeast1'
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$IMAGE_NAME', '$BUILD_PATH']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$IMAGE_NAME']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '$SERVICE_NAME', '--image', 'gcr.io/$PROJECT_ID/$IMAGE_NAME', '--region', '$REGION', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/$IMAGE_NAME