version: '3'
services:
  db:
    build: ./docker/mysql
    environment:
      - MYSQL_DATABASE=aapaca
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_USER=conv
      - MYSQL_PASSWORD=passwd
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      # for Mac
      - ./docker/mysql/conf.d:/root/conf.d
      - ./mysql:/var/lib/mysql
      # for Windows
      # - ./docker/mysql/conf.d:/etc/mysql/conf.d
      # - db-data:/var/lib/mysql
# volumes:
#   db-data:
