version: '3'
services:
  db:
    build: .
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_USER=conv
      - MYSQL_PASSWORD=passwd
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
